version: '3.3'
services:
  av-nginx-rtmp-rtsp-alpine:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "1935:1935"
      - "8554:8554"
      