trigger:
  branches:
    include:
    - "main"
  paths:
    include:
    - envs/vm/azure-vm/*

variables:
  - name: configurationFile
    value:  'avtool.azure-vm.env'

pool:
  vmImage: 'ubuntu-20.04'

stages:
- stage: TestAzureVirtualMachineServices
  displayName: Test Azure Virtual Machine Services Stage
  jobs:
  - job: TestAzureVirtualMachineServicesJob
    displayName: Test Azure Virtual Machine Services Job
    steps:     
    - task: Bash@3
      displayName: 'Install Pre-requisites'
      inputs:
        targetType: 'inline'
        script: |
          pipelines/utils/avtool.sh -a install -c $(configurationFile) -e true 

    - task: Bash@3
      displayName: 'Integration Test Services'
      inputs:
        targetType: 'inline'
        script: |
          pipelines/utils/avtool.sh -a integration -c $(configurationFile) -e true -s true
