trigger:
  branches:
    include:
    - "main"
  paths:
    include:
    - envs/container/docker/*
    - pipelines/azure-dev-ops/azure-pipelines.tests-docker.yml

variables:
  - name: configurationFile
    value:  'avtool.docker.env'

pool:
  vmImage: 'ubuntu-20.04'

stages:
- stage: TestDockerServices
  displayName: Test Docker Services Stage
  jobs:
  - job: TestDockerServicesJob
    displayName: Test Docker Services Job
    steps:     
    - task: Bash@3
      displayName: 'Install Pre-requisites'
      inputs:
        targetType: 'inline'
        script: |
          pipelines/utils/avtool.sh -a install -c $(configurationFile) -e true 

    - task: Bash@3
      displayName: 'Integration Test Services'
      inputs:
        targetType: 'inline'
        script: |
          pipelines/utils/avtool.sh -a integration -c $(configurationFile) -e true 
