trigger:
  branches:
    include:
    - "main"
  paths:
    include:
    - envs/vm/azure-vm/*
    - pipelines/azure-dev-ops/azure-pipelines.tests-azure-vm.yml

variables:
  - name: configurationFile
    value:  'avtool.azure-vm.env'
  - group: av-services-vg

pool:
  vmImage: 'ubuntu-20.04'

stages:
- stage: TestAzureVirtualMachineServices
  displayName: Test Azure Virtual Machine Services Stage
  jobs:
  - job: TestAzureVirtualMachineServicesJob
    displayName: Test Azure Virtual Machine Services Job
    steps:     
    - task: Bash@3
      displayName: 'Install Pre-requisites'
      inputs:
        targetType: 'inline'
        script: |
          pipelines/utils/avtool.sh -a install -c $(configurationFile) -e true

    - task: AzureCLI@2
      displayName: Azure Authentication  
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: "bash"
        addSpnToEnvironment: "true"
        scriptLocation: "inlineScript"
        inlineScript: |
          echo "Service Principal Id: $servicePrincipalId"
          echo "Service Principal Key: $servicePrincipalKey"
          subscriptionId=$(az account show --query 'id' --output tsv)
          tenantId=$(az account show --query 'tenantId' --output tsv)
          echo "Tenant Id: $tenantId"
          echo "Subscription Id: $subscriptionId"          

    - task: AzureCLI@2
      displayName: 'Integration Test Services'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: "bash"
        addSpnToEnvironment: "true"
        scriptLocation: "inlineScript"
        inlineScript: |
          pipelines/utils/avtool.sh -a integration -c $(configurationFile) -e true -s true
